dynamodb + db

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,9 +1,9 @@
 #! /usr/bin/bash
 
-set -e
+set -e # stop if it fails at any point
 
 if [ -z "$1" ]; then
-  echo "No TABLE_NAME argument supplied eg. bin/rds/describ-table cruddur-messages"
+  echo "No TABLE_NAME argument supplied eg ./bin/ddb/drop cruddur-messages prod "
   exit 1
 fi
 TABLE_NAME=$1
@@ -14,5 +14,7 @@ else
   ENDPOINT_URL="--endpoint-url=http://localhost:8000"
 fi
 
-aws dynamodb delete-table  $ENDPOINT_URL \
+echo "deleting table: $TABLE_NAME"
+
+aws dynamodb delete-table $ENDPOINT_URL \
   --table-name $TABLE_NAME
